### ISSUE TITLE
Отсутствие кнопок отмены и удаления статьи в карточке редакторирования

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#10]
Раньше это было так:
![image](https://user-images.githubusercontent.com/29545118/27288390-45ab51b6-550f-11e7-9be9-26024fdba2ce.png)

**Comment by Integral** [comment]
Я думаю что для того чтобы выйти из окна нужно нажать куда-нибудь вне него.
Возможно также работает esc. Сохраняется все параллельно с редактированием.
Удаление в дополнительном меню из трёх точек.

**Comment by Integral** [comment]
Крест убран, теперь есть отмена и ок, отмена возвращает статью к состоянию на момент открытия.
