### ISSUE TITLE
Проблема "соб"

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#15]
http://test.tastorona.su/#page=definitions,entityId=569a2df1d3c021100019f8ca

Задача - добавить в синонимы "Собачье вымя". После написания третьей буквы слово "Соб" автоматически добавляется как синоним. Никаких побелов или энтер не нажимается. Браузер - Хром.

![image](https://user-images.githubusercontent.com/29545118/27993985-80a9709c-64bc-11e7-9362-b5321993850f.png)

**Comment by shalomnikilom** [comment]
Временно решил проблему, напечатав отдельно и скопировав полное сочетание в поле

**Comment by Integral** [comment]
@shalomnikilom это из-за того что на букве б запятая, я разберусь с этим
