### ISSUE TITLE
Поиск по фрагменту фразы

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#18]
Не работает поиск по фрагменту фразы, который до крайности нужен.
Сравнить:
![image](https://user-images.githubusercontent.com/29545118/27994129-aef6a9c6-64bf-11e7-8b94-ab78d00f1817.png)

![image](https://user-images.githubusercontent.com/29545118/27994131-c0f3fcaa-64bf-11e7-9941-5e99c0c6aaf8.png)

**Comment by Integral** [comment]
@shalomnikilom дело в том, что там теперь полнотекстовый поиск, а был запрос с вхождением строки в заголовок или синоним
то есть это немного разные вещи, нам надо понять чему мы отдаем приоритет и хотим ли мы может быть оставить оба варианта?
если хотим, то хотим ли мы два поиска или хотим сделать поиск с какой-то опцией
