### ISSUE TITLE
Поиск по синонимам

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#19]
Не обрабатывает при поиске синонимы.
Сравни:
В старом
![image](https://user-images.githubusercontent.com/29545118/27994139-0021d096-64c0-11e7-944a-ae1f1a8de289.png)

В новом:
![image](https://user-images.githubusercontent.com/29545118/27994142-110fab76-64c0-11e7-81e5-6052c1ccbc8a.png)

**Comment by Integral** [comment]
ищет, это про то, что ты описывал в #18
