### ISSUE TITLE
При слиянии не объединяет синонимы

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#20]

**Comment by Integral** [comment]
@shalomnikilom и никогда не объединял
как ты это представляешь? может быть тогда и заголовок сливаемого тоже нужно в синонимы добавлять?

**Comment by shalomnikilom** [comment]
Это не нужно: заголовки как раз можно потом в синонимы добавить.
В идеале список синонимов конечной сущности должен включать неповторяющиеся синонимы сливаемых сущностей. И после этого хорошо бы сделать проверку на повторы и исключить одинаковые (вне зависимости от регистра букв)
