### ISSUE TITLE
Слишком мало места в правой панели

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#7]
![image](https://user-images.githubusercontent.com/29545118/27288167-99d1fb9c-550e-11e7-949f-e3253220d8ec.png)

**Comment by Integral** [comment]
Я правильно понимаю что это было в файрфоксе?
В любом случае - сейчас уже нет?

**Comment by shalomnikilom** [comment]
Это в хроме, ничего не изменилось

**Comment by shalomnikilom** [comment]
Горизонтальная прокрутка пропала. Но много пустого пространства осталось
