### ISSUE TITLE
Отсутствуют типы словарей definitions - срочно

### ISSUE THREAD

**Issue by shalomnikilom** [archivist/ost#9]
Нет возможности выбрать и изменить тип словаря, нет возможности фильтровать по типу.

![image](https://user-images.githubusercontent.com/29545118/27288316-0aa3c3c8-550f-11e7-83da-13782a385875.png)

**Comment by shalomnikilom** [comment]
Без этого никаких тестов проводить нельзя - работа будет впустую

**Comment by Integral** [comment]
Было несколько опечаток, перезалил данные - можно теперь выбрать и изменить

**Comment by shalomnikilom** [comment]
Спасибо! Ещё выборку бы по типу (но это не так срочно).
И вот такие замечания:
https://yadi.sk/i/T8KiyJAA3KPr3W

**Comment by Integral** [comment]
Ок, все кроме поставить по-умолчанию synonyms сделано - там и так написано ниже что нужно вбивать.
